# -*- coding: utf-8 -*-
"""
Created on Thu Feb  6 14:51:49 2020

@author: omeil
"""
# TIME FOR 251... <1s

import numpy as np
from Affine import Affine as A

m = np.array((1,3,5,7,9,11,15,17,19,21,23,25))
n = np.arange(0,26,1)
S = "BCBMLDSXGQTGXPMWMZLBMESZBCPBMSPZQXRSACQHBCRSMXBPQOKBBMFSZKKQZCIMLTPQIXBCUQZXMKSQZQTBMIRCXGIMLZCGGDOXDCUMOGCGBCBMLGRCHXSZXBCRQTXQTGQICGXMDRCMZLSZGHSXCQTSXMRRGBCWMGDCMOXSTORWBMXMGXMPMPXXBQOQEQOXBSZXBCICMZXSICGBCBMLBMRXCLSZTPQZXQTIMPSOGWSXBMXPMUCQTJQESZBCPRSFSLUQOZXCZMZUCMZLGQICXBSZKWBSUBPCGCIDRCLMGISRCGBCGXQQLTQPGCFCPMRIQICZXGMGXBQOKBSZUMHMDRCQTGHCCUB"

for i in range(len(m)):
    for j in range(len(n)):
        
        aff = A(m[i],n[j])
#aff.numLet(S)
        aff.encode(S, False)
        
print ("done")
