# -*- coding: utf-8 -*-
"""
Created on Thu Feb 27 21:23:42 2020

@author: omeil
"""
from Vigenere import Vigenere as Vin

key = "BOUNTY"
cipher = "OCNYBIFHBRUPBNYAZGBBNBYESSYXYYNSQVMFDCHDNCSWHTEGNPMNLRSWXRYPPAFNGBUCFNGBISLRTRPILFXYXOMUXBTIHFXRHONRLQIOFYLRBBXNFGHVNLPMNOHJBRIONBKAIKBBLCGZUZXGTHBRBKQFCFHLFRFPZFUBCAZYORBRKLBAYZHRISLBYCYWFRLDSCGUXPCSUPHLIOHQZJPKMJHPMRQVWCXSFPHKFVYEFGMRYLXQDCGZTLEHBRTGSPLVWEFRBNKZPFNUTRUKCABGUWYFYPBAYXXCQOHPBCOHFNGBTMIHKQUCLVXBQCGCBPJSMFACXWNULGMSHGEGQGABOCNSSBNPUWLRWWPILCHMSMIHKFVRXYXBNOMFXQZSUEGGOUNBUPFONUXDSSYGACXFYGVFFRLRYSTSISRMBFNRXKJBAFAMSSMRGBUVYFXRISBBFCMSMFMCNDYFMRPGNGHKFWFVYRNMFNFNCSMVWCUVYTHJESHQHMS"

vin = Vin(key)
#cipher = vin.encode(plain)

decode = vin.decode(cipher)

